### ISSUE TITLE
Talk to Adam about Switch

### ISSUE THREAD

**Issue by TrippCC** [wAlber47/NetFlow-CNCS-Capstone#13]
Ours isn't currently capable of generating NetFlow logs.

**Option A**: Continue using Cisco 3750G and only generate logs on the Router. The issue with this is that only traffic exiting the network is logged this way. 

**Option B**: Get a different switch that is compatible with NetFlow and setting up that in the network.

**Comment by wAlber47** [comment]
Talked to Adam during the Design Project #2 meeting and grabbed new Juniper EX4200 Switch during class.

**Comment by wAlber47** [comment]
Received Switch, (10/28), and implemented into network.
