### ISSUE TITLE
Cisco Switch

### ISSUE THREAD

**Issue by TrippCC** [wAlber47/NetFlow-CNCS-Capstone#2]
Set up the Cisco layer-3 switch that will be the thing generating our netflow logs

**Comment by wAlber47** [comment]
Switch is properly running and sending traffic to correct locations, currently have it only hooked up to my personal computer.

will hook up the other 3 PC's and the Pi's later

**Comment by wAlber47** [comment]
Hooked up switch to roommates' PCs, IP's are done through DHCP on the router

**Comment by wAlber47** [comment]
Pi's are hooked up the router, although as of now serve no purpose other than blank hosts with static IP addressing

**Comment by wAlber47** [comment]
Returned switch to Foster202
